// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "ai.baseUrl": string;
      "ai.apiKey": string;
      "ai.model": string;
      "outline.preview": boolean;
      "outline.backup": boolean;
      "outline.debug": boolean;
      "outline.mode": string;
      "version": string;
    };
  }
}
